//
//  User.swift
//  Async_Await_Networking
//
//  Created by Rashad Abdul-Salaam on 9/13/23.
//

import Foundation

/**
 CONTENT STRUCTURE
 
 
 List
 Data structure for all responses that return array of data.
 In case you get single item your will get it directly.

 {
 data: Array(Model)
 total: number(total items in DB)
 page: number(current page)
 limit: number(number of items on page)
 }
 User Preview
 User as a part of list or other data like post/comment.
 {
 id: String(autogenerated)
 title: String("mr", "ms", "mrs", "miss", "dr", "")
 firstName: String 2-50)
 lastName: String 2-50)
 picture: String(url)
 }
 User Full
 Full user data returned by id.
 {
 id: String(autogenerated)
 title: String("mr", "ms", "mrs", "miss", "dr", "")
 firstName: String 2-50)
 lastName: String 2-50)
 gender: String("male", "female", "other", "")
 email: String(email)
 dateOfBirth: String(ISO Date - value: 1/1/1900 - now)
 registerDate: String(autogenerated)
 phone: String(phone number - any format)
 picture: String(url)
 location: object(Location)
 }
 Location
 Using only as a part of full user data.
 {
 street: String 5-100)
 city: String 2-30)
 state: String 2-30)
 country: String 2-30)
 timezone: String(Valid timezone value ex. +7:00, -1:00)
 }
 Post Create
 Post data for create request.
 {
 text: String 6-50, preview only)
 image: String(url)
 likes: number(init value: 0)
 tags: array(String)
 owner: String(User id)
 }
 Post Preview
 Post data as a part of list.
 {
 id: String(autogenerated)
 text: String 6-50, preview only)
 image: String(url)
 likes: number(init value: 0)
 tags: array(String)
 publishDate: String(autogenerated)
 owner: object(User Preview)
 }
 Post
 Post data returned by id.
 {
 id: String(autogenerated)
 text: String 6-1000)
 image: String(url)
 likes: number(init value: 0)
 link: String(url, length: 6-200)
 tags: array(String)
 publishDate: String(autogenerated)
 owner: object(User Preview)
 }
 Comment Create
 Comment data to create new item.
 {
 message: String 2-500)
 owner: String(User Id)
 post: String(Post Id)
 }
 Comment
 {
 id: String(autogenerated)
 message: String 2-500)
 owner: object(User Preview)
 post: String(Post Id)
 publishDate: String(autogenerated)
 }
 
 */


struct User: Codable {
    
    static var sampleUser: User {
        /*
         "id": "60d0fe4f5311236168a109ca",
             "title": "ms",
             "firstName": "Sara",
             "lastName": "Andersen",
             "picture": "https://randomuser.me/api/portraits/women/58.jpg",
             "gender": "female",
             "email": "sara.andersen@example.com",
             "dateOfBirth": "1996-04-30T19:26:49.610Z",
             "phone": "92694011",
             "location": {
                 "street": "9614, SÃ¸ndermarksvej",
                 "city": "Kongsvinger",
                 "state": "Nordjylland",
                 "country": "Denmark",
                 "timezone": "-9:00"
         */
        User(
            id: "60d0fe4f5311236168a109ca",
            title: "ms",
            firstName: "Sara",
            lastName: "Andersen",
            gender: "Female",
            email: "sara.andersen@example.com",
            dateOfBirth: "1996-04-30T19:26:49.610Z",
            registerDate: "2021-06-21T21:02:07.374Z",
            phone: "92694011",
            picture: "https://randomuser.me/api/portraits/women/58.jpg",
             location: UserLocation(street: "9614, SÃ¸ndermarksvej", city: "Kongsvinger", state: "Nordjylland", country: "Denmark", timezone: "-9:00")
        )
    }
    let id: String
    let title: String
    let firstName: String
    let lastName: String
    let gender: String
    let email: String
    let dateOfBirth: String
    let registerDate: String
    let phone: String
    let picture: String
    let location: UserLocation
}

struct UserPreview: Codable, Hashable {
   let id: String
   let title: String
   let firstName: String
   let lastName: String
   let picture: String
    
}

/// Using only as a part of full user data.
struct UserLocation: Codable {
   var street: String
   var city: String
   var state: String
   var country: String
   var timezone: String
}

struct UserListData: Codable {
    static let mockUsers: [UserPreview] = [
        UserPreview(id: "60d0fe4f5311236168a109ca",
                    title: "ms",
                    firstName: "Sara",
                    lastName: "Andersen",
                    picture: "https://randomuser.me/api/portraits/women/58.jpg")
                ,
                UserPreview(
                   id: "60d0fe4f5311236168a109cb",
                   title: "miss",
                   firstName: "Edita",
                   lastName: "Vestering",
                   picture: "https://randomuser.me/api/portraits/med/women/89.jpg"
                ),
                UserPreview(
                   id: "60d0fe4f5311236168a109cc",
                   title: "ms",
                   firstName: "Adina",
                   lastName: "Barbosa",
                   picture: "https://randomuser.me/api/portraits/med/women/28.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109cd",
                    title: "mr",
                    firstName: "Roberto",
                    lastName: "Vega",
                    picture: "https://randomuser.me/api/portraits/med/men/25.jpg"
                ),
                UserPreview(
                   id: "60d0fe4f5311236168a109ce",
                   title: "mr",
                   firstName: "Rudi",
                   lastName: "Droste",
                   picture: "https://randomuser.me/api/portraits/med/men/83.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109cf",
                    title: "mrs",
                    firstName: "Carolina",
                    lastName: "Lima",
                    picture: "https://randomuser.me/api/portraits/med/women/5.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109d0",
                    title: "mr",
                    firstName: "Emre",
                    lastName: "Asikoglu",
                    picture: "https://randomuser.me/api/portraits/med/men/23.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109d1",
                    title: "mr",
                    firstName: "Kent",
                    lastName: "Brewer",
                    picture: "https://randomuser.me/api/portraits/med/men/52.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109d2",
                    title: "mr",
                    firstName: "Evan",
                    lastName: "Carlson",
                    picture: "https://randomuser.me/api/portraits/med/men/80.jpg"
                ),
                UserPreview(
                    id: "60d0fe4f5311236168a109d3",
                    title: "mr",
                    firstName: "Friedrich-Karl",
                    lastName: "Brand",
                    picture: "https://randomuser.me/api/portraits/med/men/7.jpg"
                )
    
    ]
    let data: [UserPreview]
}
